### PR TITLE
Version bump — would you update it on npm?

### PR DESCRIPTION
**Pull request by evertonfraga**
Hi! Would you please update it on npm? I've version-bumped that for you. 

https://github.com/electron/electron/issues/11861

Thanks!

### CODE REVIEW

**Comment by kachkaev** [comment]
Also looking forward to see a new version on npm @glebdmitriew! It will resolve https://github.com/guyonroche/exceljs/issues/79 🤞

**Comment by kachkaev** [comment]
Thanks for bumping the version @glebdmitriew! Do you know @seagullua (@ubrains) who appears to be a publisher for this package [on npm](https://www.npmjs.com/package/unzip2)? Could you please ask him to publish a new version? 🚀

**Comment by ghost** [comment]
Would love a update on NPM too!

**Comment by kachkaev** [comment]
@tommyriska I think the package name has changed, see https://github.com/glebdmitriew/node-unzip-2/commit/3702bce9596496bf45442e156541c68eb965b9f9

So you should be able to 

```
npm rm unzip2
npm install node-unzip-2
```
Your `require` / `import` statements will need an update too.

**Pull request merged**
